### ISSUE TITLE
Ask for help ~~~

### ISSUE THREAD

**Issue by AIBio** [VanNostrandLab/eclip#1]
Hi,

I'm sorry to open an issue irrelevant to elip pipline.
I have read the paper you published on Genome Biology in 2020 (Principles of RNA processing from analysis of enhanced CLIP maps for 150 RNA binding proteins). 
It is an excellent work, expecially in visualizing CLIPseq data.
But, I have a question abount visualize meta-gene and meta-exon peak density maps.
Because I'm skilled at programming, so could you share your code about how to plot meta-gene and meta-exon peak density maps? I really appreciate your help.

Best wishes.
Hanwen
2021/11/04

**Comment by VanNostrandLab** [comment]
Hi Hanwen,

we’re current working on making the code accessible for a public release; in the meantime can you directly email Dr. Van Nostrand ***@***.******@***.***>) and he may share the code used in the Genome Biology paper.

Best,
FEI


From: Hanwen_Yu ***@***.***>
Date: Thursday, November 4, 2021 at 7:15 AM
To: VanNostrandLab/eclip ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VanNostrandLab/eclip] Ask for help ~~~ (Issue #1)
***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________

Hi,

I'm sorry to open an issue irrelevant to elip pipline.
I have read the paper you published on Genome Biology in 2020 (Principles of RNA processing from analysis of enhanced CLIP maps for 150 RNA binding proteins).
It is an excellent work, expecially in visualizing CLIPseq data.
But, I have a question abount visualize meta-gene and meta-exon peak density maps.
Because I'm skilled at programming, so could you share your code about how to plot meta-gene and meta-exon peak density maps? I really appreciate your help.

Best wishes.
Hanwen
2021/11/04

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_VanNostrandLab_eclip_issues_1&d=DwMCaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=V9zDJIIvftG93QgqsjRmscEavsf1rzUYmn36Kmoh3Io&m=9XmPs0Qf7TXkQyTgaYXp77HNwvVh1D66CTxz1lEq8F1xR8HjOFJss93h_x6Te3pF&s=vdCVh6o7nfOeOdifUsSkKFQlPkkTl9WhbS-lUdH-o54&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASJSTMJMMQ36RAOKJCBEEELUKJ2NZANCNFSM5HLJL6MQ&d=DwMCaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=V9zDJIIvftG93QgqsjRmscEavsf1rzUYmn36Kmoh3Io&m=9XmPs0Qf7TXkQyTgaYXp77HNwvVh1D66CTxz1lEq8F1xR8HjOFJss93h_x6Te3pF&s=RhniPL_xDexYIB5ROuI-agfaCr05fTFqiCksqE7xJTs&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=V9zDJIIvftG93QgqsjRmscEavsf1rzUYmn36Kmoh3Io&m=9XmPs0Qf7TXkQyTgaYXp77HNwvVh1D66CTxz1lEq8F1xR8HjOFJss93h_x6Te3pF&s=iL-6auF3XQCaLrS3lmatFH43Y6pB-jhSbSNukz3QBW8&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=V9zDJIIvftG93QgqsjRmscEavsf1rzUYmn36Kmoh3Io&m=9XmPs0Qf7TXkQyTgaYXp77HNwvVh1D66CTxz1lEq8F1xR8HjOFJss93h_x6Te3pF&s=xbzJyBrakBqbMRQOsIOcrYTF5bP2VHNpXJszwiVjMto&e=>.

**Comment by AIBio** [comment]
Hi FEI,
Thanks for your help.
I'll try to email Dr. Van Nostrand to search some helps.
Best wishes.
Hanwen
2021/11/16
